In [2]:
def test():
    print('test() for function')
    return 
test()

test() for function


In [4]:
class demo:
    def test(self):
        print('test() for function')
        return
obj=demo()
obj.test()
    

test() for function


In [7]:
class demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
p1.fact(5)

120

In [10]:
def fact(n):
    if(n==0):
        return 1
    else:
        return n*fact(n-1)
fact(6)
    
    

720

In [19]:
class demo2:
    def accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def display(self):
        print("a=",self.p1)
        print("b=",self.p2)
c1=demo2()
c1.accept(10,20)
c1.display()

a= 10
b= 20


In [18]:
class demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=demo2(10,20)
print(c1.add(100,200))

300


In [22]:



import numpy as np
list=[1,2,3,4]
array=np.array(list)
print(array)

[1 2 3 4]


In [24]:
import numpy as np
list=[1,2,3,4]
array=np.array(list)
array+10
print(array)

[1 2 3 4]


In [25]:
import numpy as np
array=np.array(list)
print(array.shape)
print(array.dtype)

(4,)
int32


In [26]:
#reshaping the given array
#numpy.reshape(arrayname,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)


(2, 3)
(3, 2)


In [29]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [31]:


a1=np.random.normal(5,0.5,10)
print(a1)

[4.49045042 5.12929786 5.98651354 5.74845443 4.92834747 4.98958807
 4.51275107 5.36718254 5.33844124 5.06509901]


In [33]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [37]:




np.ones((4,3),dtype=np.int64)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [38]:
np.zeros((2,2),dtype=np.int64)


array([[0, 0],
       [0, 0]], dtype=int64)

In [40]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[1][3]=14
np.asarray(a)[3][3]=16
print(a)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [45]:

np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [47]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [49]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[2]=5
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [51]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [52]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing row",a1[:,1])

slicing row [2 5]


In [53]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last col:",a1[:,2])

slicing last col: [3 6]


In [56]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing row andf col:",a1[1,:1])

slicing row andf col: [4]


In [60]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row",a1[1])

second row [4 5 6]


In [61]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row",a1[0])

first row [1 2 3]


In [62]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row",a1[0])

first row [1 2 3]


In [59]:

[{"metadata":{"trusted":true},"cell_type":"code","source":"a1=np.array([(1,2,3),(4,5,6)])\nprint(\"second row\",a1[1])","execution_count":78,"outputs":[{"output_
type":"stream","text":"second row [4 5 6]\n","name":"stdout"}]}]

SyntaxError: EOL while scanning string literal (<ipython-input-59-c87ca06d1463>, line 2)

In [63]:
a1=np.random.normal(5,1,10)
print(a1)

[6.23687847 4.86546843 5.18027568 6.33476243 5.31408114 4.28831928
 4.28131722 5.33265262 4.2512832  5.85086935]


In [65]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value",np.min(a1))
print("max value",np.max(a1))
print("mean value",np.mean(a1))
print("median value",np.median(a1))

[4.95997176 5.36032072 6.10827878 5.10889139 5.12259837 5.83278979
 3.35813749 4.59099045 6.13184577 4.25287976]
min value 3.358137487321179
max value 6.131845768581674
mean value 5.082670428778025
median value 5.1157448832106045


In [67]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [69]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)


array([[ 5,  8],
       [13, 20]])

In [71]:
c1=np.array([(1,5),(6,9)])
c2=np.array([(1,3),(1,6)])
np.dot(c1,c2)


array([[ 6, 33],
       [15, 72]])